spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:test     # (2) JDBC URL
    dbcp2:
      max-total: 100
#    hikari:
#      maximum-pool-size: 100
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
  threads:
    virtual:
      enabled: true
mybatis:
  mapper-locations: classpath*:mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.virtualthread.model